version: '3.9'

services:
  tms-nginx:
    container_name: tms-nginx
    restart: always
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx:/etc/nginx/conf.d
    networks:
      - tms-network
  tms-certbot:
    image: certbot/certbot
    container_name: tms-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - tms-nginx
    command: certonly --webroot --webroot-path=/var/www/html --force-renewal --email seasle98@gmail.com -d seasky.space,www.seasky.space --agree-tos

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/frontend/build
      o: bind

networks:
  tms-network:
    external: true
