export const RESET_STORE = Symbol('RESET_STORE');
export const UPDATE_AUTHORIZED = Symbol('UPDATE_AUTHORIZED');
export const ADD_NOTIFICATION = Symbol('ADD_NOTIFICATION');
export const REMOVE_NOTIFICATION = Symbol('REMOVE_NOTIFICATION');
